skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ticket_booking = "E4mfiMWpSeubf7Vu6RmxDGEvcsM2X8tD5shQRFDTgR26"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
