[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ticket_booking = "82Tzgv6JU15FD6jQH1hLwuvBDj8VjQ2Dz1SdnonU3ciA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
